version: 2

formats: all

python:
  install:
  - requirements: docs/requirements.txt

sphinx:
  builder: html

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

submodules:
  exclude: all
