image:
  - Visual Studio 2022
  - Ubuntu2004
  - macos

environment:
  matrix:
    - version: "3.10"
    - version: "3.9"
    - version: "3.8"

test_script:
  - python -m unittest tests.py
  - python prepare.py cythonize
  - python setup.py bdist_wheel

for:
  - matrix:
      only:
        - image: Visual Studio 2022
    install:
      - "C:\\Python%version:.=%-x64\\python -m virtualenv venv"
      - venv\Scripts\activate
      - python -m pip install --pre cython wheel pyglm pillow autopep8

      - "C:\\Python%version:.=%\\python -m virtualenv venv2"
      - venv2\Scripts\activate
      - python -m pip install --pre cython wheel pyglm pillow autopep8

      - python prepare.py cythonize
      - python -m unittest tests.py # early tests
      - python setup.py bdist_wheel
      - venv\Scripts\activate
  - matrix:
      only:
        - image: Ubuntu2004
        - image: macos
    install:
      - source $HOME/venv$version/bin/activate
      - python -m pip install --pre cython wheel pyglm pillow autopep8

build: off
skip_branch_with_pr: true

artifacts:
  - path: dist/pyunity-0.9.0*
    name: Builds
