name: Testing
on: [push]
jobs:
  test:
    name: Python 3.9-x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: pip install coverage -r requirements.txt
      - name: Run tests
        env:
          full: 1
          PYUNITY_INTERACTIVE: 0
        run: coverage run -m unittest tests.py
      - name: Upload report
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f .coverage
