name: Testing
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }}-x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -r .github/build_requirements.txt -r requirements.txt
          sudo apt-get update
          sudo apt-get install libgl1-mesa-dev
      - name: Print info
        env:
          PYUNITY_TESTING: 0
        run: python -m pyunity -v
      - name: Run tests
        env:
          full: 1
          PYUNITY_INTERACTIVE: 0
        run: pytest
      - name: Run mypy
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          mypy -p pyunity
      - name: Run stubtest
        if: ${{ matrix.python-version == '3.11' }}
        env:
          PYUNITY_CHANGE_MODULE: 0
        run: |
          python -m mypy.stubtest --mypy-config-file pyproject.toml \
            --ignore-unused-allowlist --allowlist .github/stubtest-ignore.txt \
            pyunity
      - name: Generate report
        if: ${{ matrix.python-version == '3.11' }}
        run: coverage xml
      - name: Upload report
        if: ${{ matrix.python-version == '3.11' }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
