name: Trigger all builds
on: [workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow: ["coverage.yml", "linux.yml", "trigger.yml", "windows.yml"]
    name: Run ${{ matrix.workflow }}
    steps:
      - name: Trigger build
        run: |
          curl \
            -X POST \
            -u rayzchen:${{ secrets.USER_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pyunity/pyunity/actions/workflows/${{ matrix.workflow }}/dispatches \
            -d '{"ref":"develop"}'
