name: Windows Wheel Builds
on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        architecture: ["x64", "x86"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - run: |
          python -m pip install --pre cython wheel pyglm pillow autopep8
          python prepare.py
          python -m unittest tests.py # early tests
          python setup.py bdist_wheel
